### PR TITLE
Merge frontends

### PR DESCRIPTION
**Pull request by stijnstroeve**

### CODE REVIEW

**Review by DHuinink — APPROVED** [review]
looks nice

**Review by DHuinink — APPROVED** [review]
nice way to set the light dark mode for the graph

**Review by DHuinink — COMMENTED** [review]
is indeed better to make your own legend, so that's good

**Review by DHuinink — COMMENTED** [review]
nice, the only thing we still have to do about the data is that the temperature has the degrees sign

**Review by DHuinink — COMMENTED** [review]
everything looks good

**Review by DHuinink — COMMENTED** [review]
minor changes so there shouldn't be a problem

**Review by DHuinink — COMMENTED** [review]
great

**Review by DHuinink — COMMENTED** [review]
nice that it is responsive on different devices

**Review by DHuinink — COMMENTED** [review]
great work

**Comment by stijnstroeve** [comment]
[Merge frontend](https://trello.com/c/k4UyMD85/102-merge-frontend)

**Pull request merged**
